# Generated by Django 5.1.4 on 2024-12-18 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baju',
            fields=[
                ('idBaju', models.AutoField(primary_key=True, serialize=False, verbose_name='Baju')),
                ('namaBaju', models.CharField(max_length=100, verbose_name='Nama Baju')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga')),
                ('ukuran', models.CharField(max_length=10, verbose_name='Ukuran')),
                ('warna', models.CharField(max_length=20, verbose_name='Warna')),
            ],
            options={
                'verbose_name': 'Baju',
                'verbose_name_plural': 'Baju',
            },
        ),
        migrations.CreateModel(
            name='Membeli',
            fields=[
                ('idMembeli', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahBarang', models.PositiveIntegerField()),
                ('strukPembelian', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Membeli',
                'verbose_name_plural': 'Membeli',
            },
        ),
        migrations.CreateModel(
            name='Menjual',
            fields=[
                ('idMenjual', models.AutoField(primary_key=True, serialize=False, verbose_name='Menjual')),
                ('stok', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Menjual',
                'verbose_name_plural': 'Menjual',
            },
        ),
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('idPembeli', models.AutoField(primary_key=True, serialize=False, verbose_name='Pembeli')),
                ('namaDepan', models.CharField(max_length=100, verbose_name='Nama Depan')),
                ('namaBelakang', models.CharField(max_length=100, verbose_name='Nama Belakang')),
            ],
            options={
                'verbose_name': 'Pembeli',
                'verbose_name_plural': 'Pembeli',
            },
        ),
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('idToko', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Toko')),
                ('namaToko', models.CharField(max_length=100, verbose_name='Nama Toko')),
                ('alamat', models.TextField(max_length=150, verbose_name='Alamat')),
            ],
            options={
                'verbose_name': 'Toko',
                'verbose_name_plural': 'Toko',
            },
        ),
        migrations.CreateModel(
            name='DetailMembeli',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idBaju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoBaju1.baju')),
                ('idMembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoBaju1.membeli')),
            ],
            options={
                'verbose_name': 'Detail Membeli',
                'verbose_name_plural': 'Detail Membeli',
            },
        ),
        migrations.CreateModel(
            name='DetailMenjual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idBaju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoBaju1.baju')),
                ('idMenjual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoBaju1.menjual')),
            ],
            options={
                'verbose_name': 'Detail Menjual',
                'verbose_name_plural': 'Detail Menjual',
            },
        ),
        migrations.AddField(
            model_name='membeli',
            name='idPembeli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoBaju1.pembeli'),
        ),
        migrations.AddField(
            model_name='menjual',
            name='idToko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoBaju1.toko'),
        ),
    ]
